### ISSUE TITLE
[BUG] Error with a particular JSON reimport

### ISSUE THREAD

**Issue by Norc** [League-of-Foundry-Developers/foundryvtt-forien-copy-environment#7]
**Describe the bug**
Error thrown when reloading a copied environment. Reported on the behalf of BigMatt500#0974 and not personally reproduced.

**To Reproduce**
1. Try to reimport attached file

**Expected behavior**
The settings should be loaded as described.

**Screenshots**
![image](https://user-images.githubusercontent.com/64667579/121780818-05dbd200-cb70-11eb-9cb0-176628cc8e7c.png)

**Browser:**
Unknown

**Foundry Version:** 
0.7.10
**System:** 

**Additional context**

[BigMatt500_foundry-environment.json.txt](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/files/6642432/BigMatt500_foundry-environment.json.txt)
(text-ified for uploading purposes)

**Comment by Tyreal74** [comment]
I was just coming to write the same Bug report. 

Some additional information though, only seems to happen on certain key imports, I could bring in some basic settings but if i imported say core or tokenmagicfx it failed.

**Comment by sneat** [comment]
Fixed in v2.0.5

**Comment by Tyreal74** [comment]
Hi, 

this still isnt fixed im afraid. I uninstalled and reinstalled using the Raw url from the github, but still the same, Foundry 7.10
![Untitled-1](https://user-images.githubusercontent.com/20683739/126027818-cfb97b57-b6ee-48c7-a286-4f227988df02.jpg)

**Comment by sneat** [comment]
@Tyreal74 or @Norc are you able to send me the file generated by the `Export Settings` option please?

![image](https://user-images.githubusercontent.com/293277/126055645-9f87baff-d811-4291-8704-710c97ac1657.png)

The one attached to this issue is the output of the `Save as JSON` option (which can't be imported).

I still haven't been able to replicate this locally, so need one of the versions that are causing the issue.

**Comment by Tyreal74** [comment]
Please find attached - sorry for the wait :) Just remove the txt
[foundry-settings-export (2).json.txt](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-copy-environment/files/6846466/foundry-settings-export.2.json.txt)


Thanks

**Comment by sneat** [comment]
Thanks for that @Tyreal74 

I haven't been able to get the error to appear locally or on the forge :( Your provided file worked correctly, even when I created players with the same names.

Do you see the import dialog that shows the diff, or do you get the error as soon as you select the file?

Can you also please confirm that you're running version 2.0.6?

**Comment by Tyreal74** [comment]
I'm running 2.06 yes, it happens soon as I click on import.

I was running 7.10, but recently upgraded to 8.8, I've tried the import again on 8.8 and that was successful so seems to be related to 7.10

**Comment by sneat** [comment]
That's helpful, thanks @Tyreal74 

Unfortunately, I *still* can't replicate it, even on 0.7.10.

![image](https://user-images.githubusercontent.com/293277/126731411-7a05f038-cbe2-4209-9750-d4291a7e85a6.png)

I assume since you've upgraded to 8.8 you won't be able to replicate it any more. It would have been good to see the error console in case it provided a line number or anything like that.

**Comment by Tyreal74** [comment]
Yeah sorry, needed to upgrade due to a game. I'll try it on my local
instance as that's still on 7.10

**Comment by sneat** [comment]
Closing as I believe this has been fixed already but didn't get any feedback. Please re-open if it's still an issue and we can debug again.
